coverage:
  status:
    project:
      default:
        # basic
        target: auto
        base: auto 
       # advanced
        if_not_found: success
        if_ci_failed: error
        informational: false
        only_pulls: false