codecov:
  token: 9a0f4bf3-06bc-42cb-bc17-e74da18c9bfc

coverage:
  status:
    project:
      default:
        # basic
        target: auto
        base: auto 
       # advanced
        if_not_found: success
        if_ci_failed: error
        informational: false
        only_pulls: false